                   Time-stamp: <2011-01-09 10:21:10 kaesler>

* URLs

Bernstein on the Excel mechanics of the regression
  http://www.efficientfrontier.com/ef/101/roll101.htm

http://www.ifa.com/pdf/FamaFrenchThreeFactor_Tuck2003.pdf

RobertT's summary of methodology:
   http://www.bogleheads.org/forum/viewtopic.php?p=393216&highlight=#393216
   http://www.bogleheads.org/forum/viewtopic.php?t=7353&highlight=collective

The Dimensions of Stock Returns: 2002 Update:
  http://www.dfaca.com/library/articles/dimensions_stock_returns_2002/index.shtml
Dimensions of stock returns 2007:
  http://www.dfaus.com/2009/05/the-dimensions-of-stock-returns-2007.html

Ken French's data library:
  http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html
  
Estimating portfolio return:
  http://www.bogleheads.org/forum/viewtopic.php?p=37935#37935

Other people's factor exposure numbers:
  vinex:
    http://www.bogleheads.org/forum/viewtopic.php?p=101575#101575
    http://www.bogleheads.org/forum/viewtopic.php?t=8346
  vivax:
    http://www.bogleheads.org/forum/viewtopic.php?p=3356&highlight=#3356
  ishares:
    http://www.bogleheads.org/forum/viewtopic.php?p=3034#3034

  IFA article on DFA vs Vanguard:
    http://www.ifa.com/Media/Images/PDF%20files/DimensionalVs.VanguardAnalysis.pdf

  http://www.bogleheads.org/forum/viewtopic.php?p=37271&highlight=#37271
  Update to above:
  http://www.bogleheads.org/forum/viewtopic.php?p=451381&highlight=#451381
  
RobertT on how to do non-usa:
  http://www.bogleheads.org/forum/viewtopic.php?p=96280#96280

MSCI Indices for international SmB
  http://www.mscibarra.com/products/indices/

  Market: Developed Markets/World Ex Usa
  Currency: USD
  Index level: Gross
  Size: Large+Mid, Small + + Micro
  Style: None
  Frequency: Monthly
  
Interpreting regression results:
 http://www.bogleheads.org/forum/viewtopic.php?t=7881
 http://www.bogleheads.org/forum/viewtopic.php?p=91991&highlight=#91991
 
Parameters to track in spreadsheet:
  http://www.bogleheads.org/forum/viewtopic.php?p=893894&highlight=&sid=3a78fe283365c8328a49a4cb2b50d482#893894

Yahoo api
  http://www.gummy-stuff.org/Yahoo-data.htm


Ken French international data:

We form value and growth portfolios in each country using four
valuation ratios: book-to-market (B/M); earnings-price (E/P); cash
earnings to price (CE/P); and dividend yield (D/P). We form the
portfolios at the end of December each year by sorting on one of the
four ratios and then compute value-weighted returns for the following
12 months. The value portfolios (High) contain firms in the top 30% of
a ratio and the growth portfolios (Low) contain firms in the bottom
30%. There are two sets of portfolios. In one, firms are included only
if we have data on all four ratios. In the other, a firm is included
in a sort variable's portfolios if we have data for that variable. The
market return (Mkt) for the first set is the value weighted average of
the returns for only firms with all four ratios. The market return for
the second set includes all firms with book-to-market data, and Firms
is the number of firms with B/M data.

Here is the data we want: (first 4 columns)
     Value-Weight Dollar Returns      All 4 Data Items Required
                -- BE/ME --   --- E/P ---   --- CE/P --   ------  Yld  -----
          Mkt   High    Low   High    Low   High    Low   High    Low   Zero
197501  17.39  16.03  17.63  17.12  17.46  16.48  18.42  15.00  18.24   6.73
197502  13.59  15.63  12.56  15.92  11.77  15.20  12.67  14.53  12.74   6.28

* Old Procedure
=========

Download daily numbers from Yahoo as .csv.

Convert to "end of month" figures using my Emacs code.

Import into spreadsheet.


